services:
  redis:
    image: redis:7.0-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - backend

  fastapi:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - backend

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A app.workers.celery_app worker --pool=solo --loglevel=info
    volumes:
      - ./:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend

volumes:
  redis_data:

networks:
  backend:
    driver: bridge