services:
  fastapi:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    networks:
      - backend

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A app.workers.celery_app worker --pool=solo --loglevel=info
    volumes:
      - ./:/app
    networks:
      - backend

networks:
  backend:
    driver: bridge

env_file:
  - .env
